import "./globals.css";
import type { Metadata } from "next";
// import LayoutWrapper from "@/context/LayoutWrapper";
import UserProvider from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
